#!/usr/bin/env bash

set -oux pipefail

mkdir /root/src
cd /root/src/
git clone git://github.com/brydoncheyney/vagrant-lxc.git
cd vagrant-lxc
bundle install
bundle exec rake && bundle exec rake build

mkdir -p /src/builds/
cp pkg/vagrant-lxc-*.gem /src/builds/
